# Generated by Django 6.0.6 on 2026-07-07 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('review_text', models.TextField(max_length=500)),
                ('google_review_url', models.URLField(blank=True, help_text='Link to the review on Google')),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Client Review',
                'verbose_name_plural': 'Client Stories — Reviews',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')])),
                ('destination', models.CharField(max_length=150)),
                ('pickup_location', models.CharField(max_length=150)),
                ('travel_days', models.PositiveSmallIntegerField(default=1)),
                ('members', models.PositiveSmallIntegerField(default=1)),
                ('is_read', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact / Enquiry',
                'verbose_name_plural': 'Contact Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('image', models.ImageField(help_text='Recommended: 1200x900 WebP/JPG', upload_to='destinations/')),
                ('description', models.TextField(help_text='Short description used on cards and detail page')),
                ('best_time', models.CharField(help_text='e.g. October to April', max_length=100)),
                ('best_season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('monsoon', 'Monsoon')], default='winter', max_length=10)),
                ('travel_type', models.CharField(choices=[('family', 'Family'), ('couples', 'Couples'), ('pilgrimage', 'Pilgrimage'), ('friends', 'Friends'), ('adventure', 'Adventure')], default='family', max_length=15)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on Home page (max 3 recommended)')),
                ('meta_title', models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=160)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Recommended: square 800x800', upload_to='memories/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Memory Photo',
                'verbose_name_plural': 'Memories Gallery',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('owner', 'Owner Introduction'), ('staff', 'Staff Timeline Profile')], default='staff', max_length=10)),
                ('title', models.CharField(help_text="Name / role, e.g. 'Selvam — Founder & Head Driver'", max_length=150)),
                ('content', models.TextField(help_text='Rich text supported (basic HTML)')),
                ('image', models.ImageField(upload_to='story/')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Story Profile',
                'verbose_name_plural': 'Our Story — Profiles',
                'ordering': ['section', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('category', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('maxi', 'Maxi / Tempo Traveller')], default='sedan', max_length=10)),
                ('tier', models.CharField(choices=[('budget', 'Budget Friendly'), ('premium', 'Premium')], default='budget', max_length=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, help_text='Price per KM in ₹', max_digits=6)),
                ('seats', models.CharField(help_text='e.g. 4+1, 6+1, 18+1', max_length=20)),
                ('image', models.ImageField(help_text='Recommended: 1200x800 WebP/JPG', upload_to='fleet/')),
                ('description', models.CharField(help_text='Short one-line description', max_length=220)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on Home page (max 3 recommended)')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Fleet — Vehicles',
                'ordering': ['display_order', 'price_per_km'],
            },
        ),
    ]
