# Generated by Django 5.1.1 on 2026-07-13 05:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog — Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('featured_image', models.ImageField(help_text='Recommended: 1200x800 WebP/JPG', upload_to='blog/')),
                ('excerpt', models.CharField(help_text='Short summary shown on blog cards', max_length=220)),
                ('content', models.TextField(help_text='Full article content. Basic HTML allowed: <p>, <h2>, <strong>, <em>, <ul>/<li>, <a>, <img>')),
                ('author', models.CharField(default='Dreams Tours and Travels', max_length=100)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False, help_text='Uncheck to keep this post as a draft')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on Home page (max 3 recommended)')),
                ('meta_title', models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=160)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog — Posts',
                'ordering': ['-published_date', 'display_order'],
            },
        ),
    ]
