# Generated by Django 5.1.1 on 2026-07-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogcategory_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='bi-compass', help_text='Bootstrap Icons class name, e.g. bi-compass, bi-house-door, bi-car-front, bi-geo-alt', max_length=50)),
                ('description', models.CharField(help_text='Short one-line description shown on the card', max_length=220)),
                ('badge_text', models.CharField(default='Budget & Premium', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Fleet Page — Services',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
