# Generated by Django 5.1.1 on 2026-07-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='location_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='room_booking',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
