# Generated by Django 5.1.1 on 2026-07-18 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactsubmission_location_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(help_text='Where would you like to stay? e.g. Munnar, Ooty', max_length=150)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('room_type', models.CharField(choices=[('budget', 'Budget'), ('premium', 'Premium')], default='budget', max_length=10)),
                ('number_of_rooms', models.PositiveSmallIntegerField(default=1)),
                ('number_of_guests', models.PositiveSmallIntegerField(default=1)),
                ('special_requests', models.TextField(blank=True, help_text='Any special requirements (optional)')),
                ('is_read', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Room Booking',
                'verbose_name_plural': 'Room Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Travel Return Date'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Travel Start Date'),
        ),
    ]
